
{
	ADJUST_TRACKING: 'ADJUST_TRACKING',
	ADJUST_VOLUME: 'ADJUST_VOLUME',
	LOAD_PLAYLIST: 'LOAD_PLAYLIST'
	LOOP_PLAYLIST: 'LOOP_PLAYLIST'
	NEXT: 'NEXT',
	PLAY_PAUSE: 'PLAY_PAUSE',
	PREVIOUS: 'PREVIOUS',
	SHUFFLE_PLAYIST: 'SHUFFLE_PLAYLIST',
	SWAP_SKIN: 'SWAP_SKIN'
}